#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TF_DIR="$ROOT_DIR/terraform"
ANSIBLE_DIR="$ROOT_DIR/ansible"

if ! command -v terraform >/dev/null 2>&1; then
  echo "terraform is required but not installed in PATH"
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required but not installed in PATH"
  exit 1
fi

cd "$TF_DIR"

# Get terraform outputs
echo "Fetching Terraform outputs..."
TF_JSON=$(terraform output -json 2>&1) || {
  echo "ERROR: Failed to get terraform outputs. Have you run 'terraform apply' yet?"
  exit 1
}

# Extract values, with better error handling
echo "Parsing Terraform outputs..."
ALB_DNS=$(echo "$TF_JSON" | jq -r '.load_balancer_dns.value // empty' 2>/dev/null || echo "")
RDS_ENDPOINT=$(echo "$TF_JSON" | jq -r '.rds_endpoint.value // empty' 2>/dev/null || echo "")
RDS_PORT=$(echo "$TF_JSON" | jq -r '.rds_port.value // 3306' 2>/dev/null || echo "3306")
NODE_PUBLIC_IPS=($(echo "$TF_JSON" | jq -r '.drupal_node_public_ips.value[]? // empty' 2>/dev/null || echo ""))
NODE_PRIVATE_IPS=($(echo "$TF_JSON" | jq -r '.drupal_node_ips.value[]? // empty' 2>/dev/null || echo ""))

if [ -z "$RDS_ENDPOINT" ]; then
  echo "WARNING: Could not extract RDS endpoint from Terraform. Keeping placeholder."
  RDS_ENDPOINT="REPLACE_WITH_RDS_ENDPOINT"
fi

if [ ${#NODE_PUBLIC_IPS[@]} -eq 0 ]; then
  echo "ERROR: Could not extract node public IPs. Check terraform apply output."
  exit 1
fi

echo "Found RDS endpoint: $RDS_ENDPOINT"
echo "Found RDS port: $RDS_PORT"
if [ -n "$ALB_DNS" ]; then
  echo "Found load balancer DNS: $ALB_DNS"
fi
echo "Found ${#NODE_PUBLIC_IPS[@]} node(s) with public IPs: ${NODE_PUBLIC_IPS[@]}"

# Extract default DB creds from variables.tf if present
tf_default() {
  local var_name="$1"
  awk -v var="$var_name" '
    $0 ~ "variable[[:space:]]+\"" var "\"" { in_block=1 }
    in_block && /default[[:space:]]*=/ {
      sub(/.*default[[:space:]]*=[[:space:]]*"/, "")
      sub(/".*/, "")
      print
      exit
    }
    in_block && /^}/ { in_block=0 }
  ' variables.tf
}

DB_USER=$(tf_default "db_username")
DB_PASS=$(tf_default "db_password")
DB_USER=${DB_USER:-drupal_admin}
HASH_SALT=$(awk -F'"' '/^hash_salt:/ { print $2; exit }' "$ANSIBLE_DIR/group_vars/all.yml" 2>/dev/null || true)
HASH_SALT=${HASH_SALT:-$(openssl rand -hex 32)}

# Write group_vars/all.yml
mkdir -p "$ANSIBLE_DIR/group_vars"
cat > "$ANSIBLE_DIR/group_vars/all.yml" <<EOF
---
# Generated by ansible/generate_from_terraform.sh
db_host: "${RDS_ENDPOINT}"
db_port: "${RDS_PORT}"
db_name: "drupaldb"
db_user: "${DB_USER}"
db_password: "${DB_PASS}"
load_balancer_dns: "${ALB_DNS}"
hash_salt: "${HASH_SALT}"
php_version: "8.3"
EOF

echo "✓ Wrote $ANSIBLE_DIR/group_vars/all.yml"

# Generate dynamic inventory
mkdir -p "$ANSIBLE_DIR"
cat > "$ANSIBLE_DIR/inventory.ini" <<EOF
[webservers]
EOF

index=1
for ip in "${NODE_PUBLIC_IPS[@]}"; do
  echo "drupal_node_${index} ansible_host=${ip} ansible_user=ubuntu ansible_ssh_private_key_file=../keys/drupal-ssh-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> "$ANSIBLE_DIR/inventory.ini"
  index=$((index+1))
done

echo "✓ Wrote $ANSIBLE_DIR/inventory.ini with ${#NODE_PUBLIC_IPS[@]} hosts"

# Create host_vars mapping peer_private_ip for rsync using private ips ordering
mkdir -p "$ANSIBLE_DIR/host_vars"

count=${#NODE_PUBLIC_IPS[@]}
if [ "$count" -ge 2 ]; then
  for i in $(seq 1 $count); do
    host_name="drupal_node_${i}"
    # peer is the next node (wrap around)
    peer_index=$(( i % count + 1 ))
    peer_ip="${NODE_PRIVATE_IPS[$((peer_index-1))]}"
    cat > "$ANSIBLE_DIR/host_vars/${host_name}.yml" <<EOF
peer_private_ip: "${peer_ip}"
EOF
    echo "✓ Wrote host_vars/${host_name}.yml -> peer_private_ip=${peer_ip}"
  done
else
  echo "ℹ Not enough nodes for peer rsync (need >=2). Skipping host_vars."
fi

echo ""
echo "Done! Review these files before running ansible-playbook:"
echo "  - $ANSIBLE_DIR/group_vars/all.yml (verify RDS endpoint and DB password)"
echo "  - $ANSIBLE_DIR/inventory.ini (verify node IPs)"
echo "  - $ANSIBLE_DIR/host_vars/ (verify peer IPs)"
